[PG15] Port regress for 728202b63cdc
Summary:
Port regress test changes as in upstream PG commit
728202b63cdcd7fb73fdba114903ed235eb02f3a.  There are some questionable
areas:

- When running the test, the first hunk of this commit results in the
  following error

      ERROR:  could not determine which collation to use for string hashing
      HINT:  Use the COLLATE clause to set the collation explicitly.

  This error can be investigated in the future.  Optimistically adjust
  the output ordering to what upstream PG expects.
- The second hunk had YB-added explicit ordering.  Preserve it for now,
  but in the future, it may be possible to remove the ordering?  If not,
  then the earlier query may want explicit ordering, though that would
  reduce the test coverage that hit that error to begin with.

Test Plan:
Depends on D29264
Jenkins: skip

Reviewers: aagrawal, tfoucher

Reviewed By: tfoucher

Subscribers: yql

Differential Revision: https://phorge.dev.yugabyte.com/D29265